# Generated by Django 4.2 on 2023-04-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='id',
            new_name='user_id',
        ),
    ]
